# Generated by Django 2.2.2 on 2019-07-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
